swagger: '2.0'
info:
  description: |
    Trac nghiem API
  version: 1.0.0
  title: Trac Nghiem
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
- name: auth
  description: Auth for login ,logout,registration
- name: exam
  description: Take exam 
# schemes:
# - http
paths:
  /register:
    post:
      tags:
      - auth
      summary: Register a new account
      operationId : register
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Required feild
        required: true
        schema:
          $ref: '#/definitions/User'
      responses:
        404:
          description: Some error occur whlie register
          
          
  
  /login:
    post:
      tags:
      - auth
      summary: Logs user into the system
      operationId: loginUser
      produces:
      - application/json
      parameters:
      - name: email
        in: query
        description: The email for login
        required: true
        type: string
      - name: password
        in: query
        description: The password for login in clear text
        required: true
        type: string
      responses:
        200:
          description: successful operation
          schema:
            type: string
          headers:
            X-Rate-Limit:
              type: integer
              format: int32
              description: calls per hour allowed by the user
            X-Expires-After:
              type: string
              format: date-time
              description: date in UTC when token expires
        400:
          description: Invalid username/password supplied
  /logout:
    get:
      tags:
      - auth
      summary: Logs out current logged in user session
      operationId: logoutUser
      produces:
      - application/json
      parameters: []
      responses:
        default:
          description: successful operation
      security:
        - bearerAuth: []
  
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: http://petstore.swagger.io/oauth/dialog
    flow: implicit
    scopes:
      write:pets: modify pets in your account
      read:pets: read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT 
        
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      name:
        type: string
      email:
        type: string
      password:
        type: string
      phone:
        type: string
    xml:
      name: User
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
# Added by API Auto Mocking Plugin
host: localhost
basePath: /api
schemes:
 - https
 - http